import {
  BadgeCheck,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  Car,
  ChartNoAxesColumn,
  ChefHat,
  Clock,
  Coffee,
  CreditCard,
  Droplets,
  Dumbbell,
  Hammer,
  Heart,
  House,
  Key,
  Leaf,
  MapPin,
  PaintRoller,
  Phone,
  Plane,
  Ruler,
  Scissors,
  ShieldCheck,
  ShoppingBag,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Truck,
  Users,
  Utensils,
  Wine,
  Wrench,
  Zap,
  Award,
  Baby,
  Bath,
  Compass,
  Database,
  FileText,
  Flower2,
  Gem,
  Gift,
  Globe,
  Handshake,
  LayoutGrid,
  Lightbulb,
  Mail,
  Package,
  Rocket,
  Settings,
  Store,
  TrendingUp,
  Umbrella,
  type LucideIcon,
} from "lucide-react";

/** Icons that service items can use; the key is what is stored in the document. */
export const icons: Record<string, LucideIcon> = {
  star: Star,
  check: BadgeCheck,
  shield: ShieldCheck,
  clock: Clock,
  calendar: Calendar,
  phone: Phone,
  pin: MapPin,
  users: Users,
  heart: Heart,
  sparkles: Sparkles,
  zap: Zap,
  leaf: Leaf,
  car: Car,
  key: Key,
  plane: Plane,
  truck: Truck,
  utensils: Utensils,
  chef: ChefHat,
  coffee: Coffee,
  wine: Wine,
  hammer: Hammer,
  wrench: Wrench,
  paint: PaintRoller,
  droplets: Droplets,
  ruler: Ruler,
  scissors: Scissors,
  smile: Smile,
  stethoscope: Stethoscope,
  house: House,
  building: Building2,
  bag: ShoppingBag,
  card: CreditCard,
  camera: Camera,
  dumbbell: Dumbbell,
  briefcase: Briefcase,
  chart: ChartNoAxesColumn,
  gem: Gem,
  award: Award,
  umbrella: Umbrella,
  file: FileText,
  bath: Bath,
  grid: LayoutGrid,
  settings: Settings,
  bulb: Lightbulb,
  baby: Baby,
  flower: Flower2,
  gift: Gift,
  box: Package,
  store: Store,
  mail: Mail,
  handshake: Handshake,
  rocket: Rocket,
  globe: Globe,
  database: Database,
  compass: Compass,
  trending: TrendingUp,
};

export const iconNames = Object.keys(icons);
