import {
  BadgeCheck,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  Car,
  ChartNoAxesColumn,
  ChefHat,
  Clock,
  Coffee,
  CreditCard,
  Droplets,
  Dumbbell,
  Hammer,
  Heart,
  House,
  Key,
  Leaf,
  MapPin,
  PaintRoller,
  Phone,
  Plane,
  Ruler,
  Scissors,
  ShieldCheck,
  ShoppingBag,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  Truck,
  Users,
  Utensils,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Icons that service items can use; the key is what is stored in the document. */
export const icons: Record<string, LucideIcon> = {
  star: Star,
  check: BadgeCheck,
  shield: ShieldCheck,
  clock: Clock,
  calendar: Calendar,
  phone: Phone,
  pin: MapPin,
  users: Users,
  heart: Heart,
  sparkles: Sparkles,
  zap: Zap,
  leaf: Leaf,
  car: Car,
  key: Key,
  plane: Plane,
  truck: Truck,
  utensils: Utensils,
  chef: ChefHat,
  coffee: Coffee,
  wine: Wine,
  hammer: Hammer,
  wrench: Wrench,
  paint: PaintRoller,
  droplets: Droplets,
  ruler: Ruler,
  scissors: Scissors,
  smile: Smile,
  stethoscope: Stethoscope,
  house: House,
  building: Building2,
  bag: ShoppingBag,
  card: CreditCard,
  camera: Camera,
  dumbbell: Dumbbell,
  briefcase: Briefcase,
  chart: ChartNoAxesColumn,
};

export const iconNames = Object.keys(icons);
